- name: "Create secret from CSV"
  hosts: localhost
  gather_facts: false
  tasks:

  #- name: execute python script to create yaml secrets
  #  command: python3 create_secret.py

  - name: create yaml secret files
    create_secret:
      src: ./secrets.csv
    register: secrets
  
  #- debug:
  #    msg: "{{item.value}}"
  #  with_items:
  #    - "{{ secrets.data | dict2items }}"
  
  - name: create k8s secret mysecret
    kubernetes.core.k8s:
      state: present
      kubeconfig: "~/.kube/config"
      resource_definition: "{{ item.value }}"
    with_items:
      - "{{ secrets.data | dict2items }}"