- name: "Create secret from CSV"
  hosts: localhost
  gather_facts: false
  tasks:
  # Read a CSV file and print the entire lists
  - name: Read users from CSV file and return a dictionary
    community.general.read_csv:
      path: "{{ file }}"
    register: secrets
    delegate_to: localhost
    no_log: True

  - name: CREATE SECRET
    kubernetes.core.k8s:
      state: present
      kubeconfig: "~/.kube/config"
      definition: 
        apiVersion: v1
        kind: Secret
        type: Opaque             
        metadata:
          name: "{{ item.SECRET_NAME }}"
          namespace: "{{ item.NAMESPACE | lower }}"     
        data:
          my_data: "{{ item.SECRET_KEY_VALUE | b64encode }}"
    with_items:
      - "{{ secrets.list }}"

# Print secrets command
#- name: Display users
#  debug:
#    msg: "oc create secret generic {{ item.SECRET_NAME }} --from-literal={{item.SECRET_KEY_REF}}={{item.SECRET_KEY_VALUE}} -n {{item.NAMESPACE}}"
#  shell: "oc create secret generic {{ item.SECRET_NAME }} --from-literal={{item.SECRET_KEY_REF}}={{item.SECRET_KEY_VALUE}} -n {{item.NAMESPACE}}"
#  with_items:
#    - "{{ secrets.list }}"