- name: "Create secret from CSV"
  hosts: localhost
  gather_facts: false
  tasks:

  #- name: execute python script to create yaml secrets
  #  command: python3 create_secret.py

  - name: create yaml secret files
    create_secret:
  
  - name: create k8s secret mysecret
    kubernetes.core.k8s:
      state: present
      kubeconfig: "~/.kube/config"
      src: secrets.yaml
  
  - name: Remove file (delete file)
    ansible.builtin.file:
      path: ./secrets.yaml
      state: absent